"""
Data models for the B2B Sales Intelligence & Outreach Engine.
All models are plain dataclasses — no ORM dependency.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class ICP:
    """Ideal Customer Profile — parsed from free-text user input."""
    raw_text:       str
    mode:           str = "discovery"          # "discovery" | "displacement"
    industry:       list[str] = field(default_factory=list)
    geo:            list[str] = field(default_factory=list)
    stage:          list[str] = field(default_factory=list)  # Seed, Series_A, Series_B, etc.
    size_min:       int = 10
    size_max:       int = 5000
    signals:        list[str] = field(default_factory=list)  # hiring_sdrs, raised_recently, etc.
    competitor:     str = ""                   # for displacement mode
    keywords:       list[str] = field(default_factory=list)
    search_queries: list[str] = field(default_factory=list)  # generated by Claude


@dataclass
class Contact:
    """A decision maker at a company."""
    name:       str = ""
    title:      str = ""
    linkedin:   str = ""
    email:      str = ""
    seniority:  str = ""   # C-Suite, VP, Director, Manager


@dataclass
class Lead:
    """Enriched company lead."""
    id:             str = ""
    company_name:   str = ""
    domain:         str = ""
    linkedin_url:   str = ""
    crunchbase_url: str = ""
    description:    str = ""
    industry:       str = ""
    geo:            str = ""
    headcount:      str = ""           # "51-200", "201-500", etc.
    funding_stage:  str = ""           # Series A, Series B, etc.
    funding_amount: str = ""           # "$30M"
    funding_date:   str = ""
    tech_stack:     list[str] = field(default_factory=list)
    hiring_signals: list[str] = field(default_factory=list)  # roles being hired
    contacts:       list[Contact] = field(default_factory=list)
    score:          float = 0.0        # 0–100 ICP match score
    score_reasons:  list[str] = field(default_factory=list)
    intent_signals: list["IntentSignal"] = field(default_factory=list)
    discovered_at:  str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    source_urls:    list[str] = field(default_factory=list)
    status:         str = "new"        # new | enriched | emailed | replied | converted


@dataclass
class IntentSignal:
    """Buying intent event detected from a review site, forum, or job board."""
    id:             str = ""
    intent_type:    str = ""   # switching_intent | pain_point | budget_available | active_evaluation
    source:         str = ""   # g2 | reddit | hacker_news | glassdoor | capterra
    source_url:     str = ""
    quote:          str = ""   # the exact text that triggered the signal
    company_mentioned: str = ""   # competitor or product mentioned
    lead_match:     str = ""   # matched lead ID if applicable
    confidence:     float = 0.0
    detected_at:    str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")


@dataclass
class PersonalizationContext:
    """Live context fetched for a lead before email generation."""
    lead_id:        str = ""
    blog_title:     str = ""
    blog_url:       str = ""
    blog_excerpt:   str = ""
    press_release:  str = ""
    recent_funding: str = ""
    job_openings:   list[str] = field(default_factory=list)   # key roles being hired
    pain_points:    list[str] = field(default_factory=list)   # inferred from jobs/content
    achievements:   list[str] = field(default_factory=list)   # recent wins to congratulate
    talking_points: list[str] = field(default_factory=list)   # ranked by relevance
    fetched_at:     str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")


@dataclass
class OutreachEmail:
    """Generated outreach email for a lead."""
    id:              str = ""
    lead_id:         str = ""
    sequence_step:   int = 1           # 1, 2, 3 (follow-ups)
    delay_days:      int = 0           # days after previous step
    subject:         str = ""
    body:            str = ""
    linkedin_dm:     str = ""
    personalization_tokens: dict = field(default_factory=dict)
    generated_at:    str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    sent_at:         str = ""
    status:          str = "draft"     # draft | sent | opened | replied | bounced


@dataclass
class CRMEntry:
    """CRM log record for a lead + outreach sequence."""
    lead_id:         str = ""
    company_name:    str = ""
    contact_name:    str = ""
    contact_title:   str = ""
    emails:          list[OutreachEmail] = field(default_factory=list)
    status:          str = "prospecting"
    notes:           str = ""
    logged_at:       str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    crm_url:         str = ""          # URL if synced to external CRM
